var _0x760d=["\x64\x69\x73\x70\x6C\x61\x79","\x69\x6E\x6C\x69\x6E\x65\x2D\x62\x6C\x6F\x63\x6B","\x63\x73\x73","\x23\x63\x6c\x6f\x73\x65\x61\x72\x74","\x44\x65\x73\x69\x67\x6e\x65\x64\x20\x62\x79\x20\x3C\x61\x20\x68\x72\x65\x66\x3D\x22\x68\x74\x74\x70\x73\x3A\x2F\x2F\x66\x61\x63\x65\x62\x6f\x6f\x6b\x2e\x63\x6f\x6d\x2f\x63\x6c\x6f\x73\x65\x61\x72\x74\x2e\x69\x64\x22\x3E\x43\x6c\x6f\x73\x65\x20\x41\x72\x74\x3C\x2F\x61\x3E","\x68\x74\x6D\x6C","\x6C\x65\x6E\x67\x74\x68","\x23\x63\x6c\x6f\x73\x65\x61\x72\x74","\x68\x72\x65\x66","\x6C\x6F\x63\x61\x74\x69\x6F\x6E","\x68\x74\x74\x70\x73\x3A\x2F\x2F\x66\x61\x63\x65\x62\x6f\x6f\x6b\x2e\x63\x6f\x6d\x2f\x63\x6c\x6f\x73\x65\x61\x72\x74\x2e\x69\x64","\x72\x65\x61\x64\x79"];$(document)[_0x760d[11]](function(){$(_0x760d[3])[_0x760d[2]](_0x760d[0],_0x760d[1]);$(_0x760d[3])[_0x760d[5]](_0x760d[4]);setInterval(function(){if(!$(_0x760d[7])[_0x760d[6]]){window[_0x760d[9]][_0x760d[8]]=_0x760d[10]}},3000)});
// Turn off lights
        $(document).ready(function(){
            $("#shadow").css("height", $(document).height()).hide();
            $(".lightSwitcher").click(function(){
                $("#shadow").toggle();
                if ($("#shadow").is(":hidden"))
                    $(this).html("Mode Bioskop").removeClass("turnedOff");
                 else
                    $(this).html("Mode Biasa").addClass("turnedOff");
            });
            
        });
	function hidediv(id) {
		document.getElementById(id).style.display = 'none';
	}
function closeart_serie(e){document.write('<ul class="label_with_thumbs">');for(var t=0;numposts>t;t++){var n,i=e.feed.entry[t],r=i.title.$t;if(t==e.feed.entry.length)break;for(var l=0;l<i.link.length;l++){if("replies"==i.link[l].rel&&"text/html"==i.link[l].type)var o=i.link[l].title,u=i.link[l].href;if("alternate"==i.link[l].rel){n=i.link[l].href;break}}var m;try{m=i.media$thumbnail.url}catch(h){s=i.content.$t,a=s.indexOf("<img"),b=s.indexOf('src="',a),c=s.indexOf('"',b+5),d=s.substr(b+5,c-b-5),m=-1!=a&&-1!=b&&-1!=c&&""!=d?d:"http://2.bp.blogspot.com/_IKigl6y9hFA/TMdcT1jzo5I/AAAAAAAAAHA/hAKuT9rJpFU/noimage.jpg"}var f=i.published.$t,p=f.substring(0,4),v=f.substring(5,7),g=f.substring(8,10),w=new Array;if(w[1]="Jan",w[2]="Feb",w[3]="Mar",w[4]="Apr",w[5]="May",w[6]="Jun",w[7]="Jul",w[8]="Aug",w[9]="Sep",w[10]="Oct",w[11]="Nov",w[12]="Dec",document.write('<li class="serie">'),1==showpostthumbnails&&document.write('<a class="categ_athumb" href="'+n+'" target ="_top"><img class="categ_thumb" title="'+r+'" src="'+m+'"/></a>'),document.write('<a class="categ_labels" href="'+n+'" target ="_top">PV/MV ANIME</a>'),"content"in i)var y=i.content.$t;else if("summary"in i)var y=i.summary.$t;else var y="";var A=/<\S[^>]*>/g;if(y=y.replace(A,""),1==showpostsummary)if(y.length<numchars)document.write(""),document.write(y),document.write("");else{document.write(""),y=y.substring(0,numchars);var $=y.lastIndexOf(" ");y=y.substring(0,$),document.write(y+"..."),document.write("")}var x="",_=0;document.write(""),document.write('<a class="categ_jdl" href="'+n+'" target ="_top">'+r+"</a>"),1==showpostdate&&(x=x+'<span class="categ_date">'+'<i class="glyphicon-time"></i>'+w[parseInt(v,10)]+" "+g+"   "+p+'</span>',_=1),1==showcommentnum&&(1==_&&(x+=" "),"1"==o&&(o="1"),"0"==o&&(o="0"),o='<a class="categ_cmnt" href="'+u+'" target ="_top">'+'<i class="glyphicon-comment"></i>'+o+"</a>",x+=o,_=1),1==displaymore&&(1==_&&(x+=''),x=x+'<a href="'+n+'" class="url" target ="_top">More ?</a>',_=1),document.write(x),document.write("</li>"),1==displayseparator&&t!=numposts-1&&document.write("")}document.write("</ul>")}
function showLucky(root){var feed=root.feed;var entries=feed.entry||[];var entry=feed.entry[0];for(var j=0;j<entry.link.length;++j){if(entry.link[j].rel=="alternate"){window.location=entry.link[j].href}}}function fetchLuck(luck){script=document.createElement('script');script.src='/feeds/posts/summary?start-index='+luck+'&max-results=1&alt=json-in-script&callback=showLucky';script.type='text/javascript';document.getElementsByTagName('head')[0].appendChild(script)}function readLucky(root){var feed=root.feed;var total=parseInt(feed.openSearch$totalResults.$t,10);var luckyNumber=Math.floor(Math.random()*total);luckyNumber++;fetchLuck(luckyNumber)}

function feelingLucky(){var script=document.createElement('script');script.type='text/javascript';script.src='/feeds/posts/summary?max-results=0&alt=json-in-script&callback=readLucky';document.getElementsByTagName('head')[0].appendChild(script)}

(function(a){a.fn.simpleTab=function(b){b=jQuery.extend({active:1,fx:null,showSpeed:400,hideSpeed:400,showEasing:null,hideEasing:null,show:function(){},hide:function(){},change:function(){}},b);return this.each(function(){var e=a(this),c=e.children("[data-tab]"),d=b.active-1;e.addClass("simpleTab").prepend('<ul class="wrap-tab"></ul>');c.addClass("content-tab").each(function(){a(this).hide();e.find(".wrap-tab").append('<li><a href="#">'+a(this).data("tab")+"</a></li>")}).eq(d).show();e.find(".wrap-tab a").on("click",function(){var f=a(this).parent().index();a(this).closest(".wrap-tab").find(".activeTab").removeClass("activeTab");a(this).addClass("activeTab");if(b.fx=="slide"){if(c.eq(f).is(":hidden")){c.slideUp(b.hideSpeed,b.hideEasing,function(){b.hide.call(e)}).eq(f).slideDown(b.showSpeed,b.showEasing,function(){b.show.call(e)})}}else{if(b.fx=="fade"){if(c.eq(f).is(":hidden")){c.hide().eq(f).fadeIn(b.showSpeed,b.showEasing,function(){b.show.call(e)})}}else{if(b.fx=="fancyslide"){if(c.eq(f).is(":hidden")){c.slideUp(b.hideSpeed,b.hideEasing,function(){b.hide.call(e)}).eq(f).delay(b.hideSpeed).slideDown(b.showSpeed,b.showEasing,function(){b.show.call(e)})}}else{if(c.eq(f).is(":hidden")){c.hide().eq(f).show()}}}}b.change.call(e);return false}).eq(d).addClass("activeTab")})}})(jQuery);(function(){var e=document.getElementsByTagName("pre"),t=e.length;for(var n=0;n<t;n++){e[n].innerHTML='<span class="line-number"></span>'+e[n].innerHTML+'<span class="cl"></span>';var r=e[n].innerHTML.split(/\n/).length;for(var i=0;i<r;i++){var s=e[n].getElementsByTagName("span")[0];s.innerHTML+="<span>"+(i+1)+"</span>"}}})();$(document).ready(function(){$("#contact").appendTo(".contact-form");$(".contact-form #contact").css("display","block");$(".post-tabs").simpleTab({active:1,fx:"fade",showSpeed:400,hideSpeed:400})});$(document).ready(function(){$(".cmm-tabs").simpleTab({active:1,fx:"fade",showSpeed:400,hideSpeed:400});$('.blogger-tab').append($('#comments'));$(".cmm-tabs.simpleTab .wrap-tab").wrap("<div class='cmm-tabs-header'/>");$('.cmm-tabs-header').prepend('<h3>Discussion</h3>');});